# Generated by Django 5.2.16 on 2026-08-10 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_booking_is_cancelled_foodorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='payment_mode',
            field=models.CharField(choices=[('Online', 'Paid While Booking (Online)'), ('OnTrain', 'Pay on Train (Cash/UPI)')], default='Online', max_length=20),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='railway.booking'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='station_stop',
            field=models.CharField(default='Station', max_length=100),
        ),
    ]
