# Generated by Django 5.2.16 on 2026-08-10 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0006_emergencyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationCrowdRadar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100)),
                ('platform_number', models.CharField(default='1', max_length=10)),
                ('congestion_level', models.CharField(default='Moderate', max_length=50)),
                ('estimated_arrival', models.CharField(default='On Time', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_stats', to='railway.train')),
            ],
        ),
    ]
