# Generated by Django 5.2.16 on 2026-08-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0007_stationcrowdradar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_identifier', models.CharField(max_length=10)),
                ('coach_type', models.CharField(max_length=50)),
                ('position_index', models.IntegerField(default=1)),
                ('is_pantry', models.BooleanField(default=False)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='railway.train')),
            ],
        ),
    ]
