# Generated by Django 5.2.16 on 2026-08-10 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0008_coachlayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_number', models.CharField(max_length=10)),
                ('scheduled_time', models.TimeField()),
                ('expected_arrival', models.TimeField()),
                ('status_message', models.CharField(default='ON TIME', max_length=100)),
                ('announcement_notice', models.CharField(blank=True, max_length=200, null=True)),
                ('train', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_info', to='railway.train')),
            ],
        ),
    ]
