# Generated by Django 5.2.16 on 2026-08-10 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_stationplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnrPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr_number', models.CharField(max_length=10, unique=True)),
                ('passenger_name', models.CharField(max_length=100)),
                ('current_status', models.CharField(max_length=50)),
                ('confirmation_probability', models.IntegerField()),
                ('prediction_trend', models.CharField(max_length=100)),
                ('chart_status', models.CharField(default='CHART NOT PREPARED', max_length=50)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.train')),
            ],
        ),
    ]
