# Generated by Django 5.2.16 on 2026-08-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0010_pnrprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_class', models.CharField(max_length=10)),
                ('seat_number', models.CharField(max_length=20)),
                ('travel_date', models.DateField()),
                ('is_booked', models.BooleanField(default=False)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.train')),
            ],
        ),
    ]
