# Generated by Django 5.2.16 on 2026-08-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0011_trainseat'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainseat',
            name='seat_type',
            field=models.CharField(choices=[('WINDOW', 'Window Seat'), ('AISLE', 'Aisle Seat'), ('MIDDLE', 'Middle / General'), ('LOWER', 'Lower Berth (Senior/Pref)')], default='WINDOW', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainseat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
